version: '3.5'
services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: calendapp
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      FLASK_ENV: development
    links:
      - postgres
    restart: on-failure
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: calendapp
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always
    